[workspace]
members = ["client", "types", "jsonrpc"]
exclude = ["integration_test", "bitcoind"]
resolver = "2"

[patch.crates-io.corepc-client]
path = "client"

[patch.crates-io.corepc-types]
path = "types"

[patch.crates-io.jsonrpc]
path = "jsonrpc"
